# ~/.config/alacritty/alacritty.toml

# Window settings
[window]
padding = { x = 8, y = 8 }
dynamic_title = true
decorations = "Full"
opacity = 0.9

# Font settings
[font]
normal      = { family = "HackGen35 Console NF", style = "Regular" }
bold        = { family = "HackGen35 Console NF", style = "Bold" }
italic      = { family = "HackGen35 Console NF", style = "Italic" }
size        = 12.0
offset      = { x = 0, y = 0 }

# Scrollback buffer
[scrolling]
history     = 10000

[keyboard]

# Shell (use Fish)
[terminal.shell]
program     = "/opt/homebrew/bin/fish"
args        = ["--login"]

# Key bindings
[[keyboard.bindings]]
key         = "V"
mods        = "Control|Shift"
action      = "Paste"

[[keyboard.bindings]]
key         = "C"
mods        = "Control|Shift"
action      = "Copy"

[[keyboard.bindings]]
key         = "PageUp"
mods        = "Shift"
action      = "ScrollPageUp"

[[keyboard.bindings]]
key         = "PageDown"
mods        = "Shift"
action      = "ScrollPageDown"

[terminal]
